app1/carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart_change/<int:product_id>/', views.cart_change, name='cart_change'),
    path('cart_remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    
]

app1/main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

app1/carts/models.py
from django.db import models

# Create your models here.

app1/carts/views.py
from django.shortcuts import render

def cart_add(request, product_id):
    ...

def cart_change(request, product_id):
    ...

def cart_remove(request, product_id):
    ...

app1/carts/templates/carts/includes/included_cart.html
{% load static %}

<div class="card mb-3 text-bg-light shadow-lg">
    <div class="card-header">
        <h5 class="card-title">Товар</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="row text-center">
                <div class="col p-0">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-dark btn-sm decrement"
                                data-cart-id="" data-cart-change-url="">-</button>
                        </span>
                        <input type="text" class="form-control number" value="1"
                            readonly>
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-dark btn-sm increment"
                                data-cart-id="" data-cart-change-url="">+</button>
                        </span>
                    </div>
                </div>
                <div class="col p-0">
                    <p>x 100.00 = </p>
                </div>
                <div class="col p-0"><strong>100.00 $</strong></div>
                <div class="col p-0">
                    <a href="{% url "cart:cart_remove" 1 %}" class="remove-from-cart" data-cart-id="">
                        <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                            alt="Catalog Icon" width="16" height="16">
                    </a>
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
        <h4 class="float-left"><strong>100.00 $</strong></h4>
    </div>
</div>